### ISSUE TITLE
locale and language of contracts and agreements?

### ISSUE THREAD

**Issue by chaals** [ethereum-oasis-op/baseline-standard#199]
Does a contract have to be written in a language spoken by both the parties? Do any of the parties' locations play any role in determining the competent jurisdiction?

Given that there is a requirement for a "legally binding" contract this seems important, since obviously a contract needs to be valid in the relevant jurisdiction(s) to e legally binding. (E.g. certain classes of person are legally incapable of being a party to a binding contract at least in certain jurisdictions).

**Comment by Kasshern** [comment]
@chaals if the parties involved have signed a legal agreement and decide to derive their commercial document for their baselined systems said legal agreement, wouldn't the answer to those questions already be established within local and international law? If Their legal agreement does not adhere to contract and jurisdiction law already existing, then it is potentially not a valid legally binding agreement, no?

**Comment by Therecanbeonlyone1969** [comment]
@chaals this is a very good and important point. I agree with @Kasshern ... this is up to counterparties and should not be further specified as it is strongly context-dependent. With the internationalization/localization recommendations, this is about as far we could/should go in the standard, IMHO.

**Comment by chaals** [comment]
> If Their legal agreement does not adhere to contract and jurisdiction law already existing, then it is potentially not a valid legally binding agreement, no?

It is *potentially* not a legally binding agreement. Which means they have Schroedinger's conformance to the spec.

A large chunk of civil law is testing whether individual parts of an agreement are enforceable - and this is usually based on what actually happens, not just a theroetical analysis of the agreement (because in many jurisdictions there has to be a claim of material impact before a civil case will be accepted).

**Comment by Therecanbeonlyone1969** [comment]
Spec is a PSD. Closing this issue. It is a requirement that counterparties must attest to. Whether they do so truthfully is a different matter and outside of the scope of the spec.
